### ISSUE TITLE
!!!ERROR: `SQLITE_NOTADB: sqlite3 result code 26: file is not a database`

### ISSUE THREAD

**Issue by Dongbox** [qwtel/sqlite-viewer-vscode#52] opened 2024-05-06 07:12 UTC
The Newest version(0.4.8) now and then shows: `SQLITE_NOTADB: sqlite3 result code 26: file is not a database`.

`Refresh Button` can solve it but it still will happen when opening the new one.

![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/36894425/032ba4b9-7f70-4b81-9cec-3ff03caa9c49)

**Comment by florian-imi** [comment] 2024-05-06 07:21
Please provide an example file.

Downgrading to the latest non-prerelease version should fix it in the meantime:

<img width="322" alt="Screenshot 2024-05-06 at 14 12 16" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/108846768/f8426399-eb2d-43ad-89a5-f6e8c5f3b417">
<img width="250" alt="Screenshot 2024-05-06 at 14 12 51" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/108846768/b8371079-7887-47d6-b1a5-d30e0e0b4251">

**Comment by qwtel** [comment] 2024-05-06 07:30
Can you provide an example file and/or determine which version introduced this behavior? 

<img width="322" alt="Screenshot 2024-05-06 at 14 12 16" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/951987/6521b63b-1ded-4143-b1c8-a1da19b5f13a">

**Comment by Dongbox** [comment] 2024-05-06 09:09
Because it is private data, I am sorry that I cannot provide an example .db data.

But, I found that the problem only occurred when opening the remote .db file when using `remote ssh`, and there was no problem when opening it in local mode.

I have been using this plugin for the past two years and this problem first occurred after updating to the new version after Labor Day.

Thanks guys.

**Comment by accountForIssues** [comment] 2024-05-06 09:19
I can confirm the same. Locally, version 0.4.8 has no issues.

Using `remote ssh` however, version 0.4.5 seems to work. Installing version >= 0.4.6 seems to throw the error.

**Comment by qwtel** [comment] 2024-05-06 09:49
> Using remote ssh however, version 0.4.5 seems to work. Installing version >= 0.4.6 seems to throw the error.

Thanks, that narrows it down, I think I know what the issue is.

**Comment by qwtel** [comment] 2024-05-06 11:08
Fixed in v0.4.9. Thanks everyone for reporting this.

**Closed by qwtel** 2024-05-06 11:08 UTC
